// core.special tests — scipy golden table (test/golden/special-values.json,
// generated by test/capture/gen-special-values.py, scipy 1.17.1) + identities.
//
// Tolerances agreed for M4 (do NOT loosen silently — renegotiate in the plan):
//   hermiteNorm vs scipy   rel error < 1e-10 for n <= 20, < 1e-8 for n = 50, 60
//     — this is the proof of the stable recurrence: the naive
//     H_n-then-normalize route loses far more than 1e-8 by n = 60. Measured
//     agreement is ~1e-13; denominators use max(|ref|, 1e-300) (no grid point
//     sits near a zero; exact-zero refs do not occur in the table).
//   assocLegendre (condonShortley=true) vs scipy lpmv   |err| < 1e-10 * max(|ref|, 1)
//     — lpmv INCLUDES the Condon-Shortley phase; refs span 0 to ~1e4.
//     flag=false must equal (-1)^m * lpmv exactly (phase-only difference).
//   assocLaguerre vs scipy genlaguerre   |err| < 1e-10 * max(|ref|, 1).
//   erf vs scipy   abs error < 2e-7 (A&S 7.1.26 max error ~1.5e-7 by design).

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { hermiteNorm, assocLegendre, assocLaguerre, erf } from '../../core/special.js';

const table = JSON.parse(
  readFileSync(new URL('../golden/special-values.json', import.meta.url), 'utf8'));

/* ================= hermiteNorm ================= */

test('hermiteNorm: matches scipy psi_n for n in {0,1,5,20,50,60} (stable recurrence)', () => {
  for (const row of table.hermite) {
    const rtol = row.n <= 20 ? 1e-10 : 1e-8;
    row.x.forEach((x, i) => {
      const ref = row.psi[i];
      const rel = Math.abs(hermiteNorm(row.n, x) - ref) / Math.max(Math.abs(ref), 1e-300);
      assert.ok(rel < rtol, `n=${row.n} x=${x}: rel ${rel}`);
    });
  }
});

test('hermiteNorm: analytic anchors and finiteness at high n', () => {
  assert.ok(Math.abs(hermiteNorm(0, 0) - Math.pow(Math.PI, -0.25)) < 1e-15, 'psi_0(0) = pi^{-1/4}');
  assert.equal(hermiteNorm(1, 0), 0, 'psi_1 odd -> zero at origin');
  assert.equal(hermiteNorm(61, 0), 0, 'odd n exact zero at origin');
  assert.ok(Number.isFinite(hermiteNorm(60, 8)), 'no overflow at n=60');
  assert.throws(() => hermiteNorm(-1, 0), RangeError);
  assert.throws(() => hermiteNorm(1.5, 0), RangeError);
});

/* ================= assocLegendre ================= */

test('assocLegendre condonShortley=true matches scipy lpmv for l=0..6, m=-l..l', () => {
  for (const row of table.legendre) {
    row.x.forEach((x, i) => {
      const ref = row.p[i];
      const err = Math.abs(assocLegendre(row.l, row.m, x) - ref);
      assert.ok(err < 1e-10 * Math.max(Math.abs(ref), 1),
        `l=${row.l} m=${row.m} x=${x}: err ${err} vs ref ${ref}`);
    });
  }
});

test('assocLegendre condonShortley=false is (-1)^m times the lpmv value', () => {
  for (const row of table.legendre) {
    const sign = Math.abs(row.m) % 2 === 0 ? 1 : -1;
    row.x.forEach((x, i) => {
      const cs = assocLegendre(row.l, row.m, x, { condonShortley: true });
      const noCs = assocLegendre(row.l, row.m, x, { condonShortley: false });
      assert.equal(noCs, sign * cs, `l=${row.l} m=${row.m} x=${x}: phase-only difference`);
      const err = Math.abs(noCs - sign * row.p[i]);
      assert.ok(err < 1e-10 * Math.max(Math.abs(row.p[i]), 1), `vs table: ${err}`);
    });
  }
});

test('assocLegendre: guards and edge cases', () => {
  assert.equal(assocLegendre(2, 3, 0.5), 0, '|m| > l -> 0');
  assert.equal(assocLegendre(1, -2, 0.5), 0, '|m| > l -> 0 (negative m)');
  assert.ok(Math.abs(assocLegendre(2, 0, 0.3) - (3 * 0.09 - 1) / 2) < 1e-14, 'm=0 is plain P_2');
  assert.throws(() => assocLegendre(-1, 0, 0), RangeError);
  assert.throws(() => assocLegendre(2, 0.5, 0), RangeError);
});

/* ================= assocLaguerre ================= */

test('assocLaguerre matches scipy genlaguerre on hydrogen (n-l-1, 2l+1) pairs, n<=7', () => {
  for (const row of table.laguerre) {
    row.x.forEach((x, i) => {
      const ref = row.L[i];
      const err = Math.abs(assocLaguerre(row.n, row.k, x) - ref);
      assert.ok(err < 1e-10 * Math.max(Math.abs(ref), 1),
        `n=${row.n} k=${row.k} x=${x}: err ${err} vs ref ${ref}`);
    });
  }
});

test('assocLaguerre: closed forms and guards', () => {
  assert.equal(assocLaguerre(0, 3, 2.5), 1, 'L_0 = 1');
  assert.equal(assocLaguerre(1, 2, 0.5), 1 + 2 - 0.5, 'L_1^{(k)} = 1 + k - x');
  assert.throws(() => assocLaguerre(-1, 0, 0), RangeError);
});

/* ================= erf ================= */

test('erf matches scipy within the A&S 7.1.26 error bound (2e-7 abs)', () => {
  table.erf.x.forEach((x, i) => {
    const err = Math.abs(erf(x) - table.erf.y[i]);
    assert.ok(err < 2e-7, `x=${x}: abs err ${err}`);
  });
  // The A&S polynomial leaves a ~1e-9 residual at x = 0 (within its bound).
  assert.ok(Math.abs(erf(0)) < 2e-9, `erf(0) = ${erf(0)}`);
  assert.equal(erf(-1.3), -erf(1.3), 'odd symmetry exact by construction');
});
